site_name: Guia de Acessibilidade Digital
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Escuro
      primary: #03161A
      accent: black
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo Claro  
      primary: #03161A
      accent: black
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
nav:
  - Introdução: index.md
  - Desenvolvimento: 
    - HTML,Semântica e estrutura da página: grupo2 /semantica.md
    - Navegação em celular e computador: nav_cel_pc.md
    - Navegação 100% por teclado: nav_tec.md
    - Foco Visível: foco_vis.md
    - Pausar, parar ou ocultar conteúdo: ppo.md
    - Áreas de clique: area_clique.md
    - Design responsivo: des_res.md
    - Uso da cor: uso_cor.md
    - Contraste da cor: contr_cor.md
    - Alto contraste e tamanho da fonte: ac_tam.md
    - Ampliação da tela: ampl.md
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc