site_name: Guia de Acessibilidade Digital

repo_name: "Guia de acessiblidade"
repo_url: "https://github.com/joseandre25/IHC-G02-Guia-De-Acessibilidade"

nav:
  - Introdução: index.md
  - Guia de Desenvolvimento: 
    - Acessibilidade em Navegação e Design: topics/grupo1.md
    - Semântica, Estrutura da Página e HTML: topics/grupo2.md
    - Testes, Checklists e Recursos: topics/grupo3.md
    - Conteúdo e Usabilidade em Textos: topics/grupo4.md
    - Formulários, Modais e Feedback de Erros: topics/grupo5.md
  - Heurísticas: heuristicas.md

theme:
  name: material  
  icon:
    set: material
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light  
      toggle:
        icon: material/weather-night
        name: Modo Escuro
      primary: #03161A
      accent: black
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo Claro  
      primary: #03161A
      accent: black
      
  font:
    text: Roboto
    code: "sans-serif"
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.pills
    - navigation.expand
    - navigation.tracking
    - content.code.annotate
    - content.code.highlight
    - content.code.linenumbers
    - content.footnotes
    - content.heading.permalinks
    - content.heading.anchor
    - content.heading.toc

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true