site_name: Guia de Acessibilidade Digital
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Escuro
      primary: #03161A
      accent: black
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo Claro  
      primary: #03161A
      accent: black
  font:
    text: Roboto
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
nav:
  - Introdução: index.md
  - Desenvolvimento: 
    - Acessibilidade em Navegação e Design: topics/grupo1.md
    - Semântica e Estrutura da Página: topics/grupo2.md
    - Testes, Checklists e Recursos: topics/grupo3.md
    - Conteúdo e Usabilidade em Textos: topics/grupo4.md
    - Formulários, Modais e Feedback de Erros: topics/grupo5.md